title: Shehryar Ahmad
logo: "/images/logo.png?raw=true"

<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

title: Shehryar  # your name (or website title) here
title: Shehryar Ahmad # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Data Scientist with 2 years experience.  
  <br><br>
  <br><br>
  
<a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
