title: Shehryar Ahmad
logo: "/images/Linked_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 2 years experience. 
  Experienced in developing end to end machine learning pipelines. 
  MSc Machine Learning and Artificial Intelligence from the University of Birmingham.
  
  
  
  
  <br><br>
  <a href="https://www.linkedin.com/in/shehryar01/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
